# Generated by bend-spike/heat/emit.bend (Bend 2). Do not edit.
# Scheme: D u_i' = w_l u_{i-1} + w_c u_i + w_r u_{i+1}, r = alpha dt / dx^2 = p / D
# weights [w_l, w_c, w_r] = [1, 2, 1], D = 4
# raw IR:        Add(Mul(Const 1, Var 0), Add(Mul(Const 2, Var 1), Add(Mul(Const 1, Var 2), Const 0)))
# simplified IR: Add(Var 0, Add(Mul(Const 2, Var 1), Var 2))
# LAWS.bend/PROOF.bend: eval(simplify(e)) == eval(e) for every window (simplify_sound).
import jax
import jax.numpy as jnp

jax.config.update('jax_enable_x64', True)

D = 4.0


@jax.jit
def step(u):
    # one explicit Euler step; u[0] and u[-1] are Dirichlet boundaries and stay put
    inner = (u[:-2] + ((2.0 * u[1:-1]) + u[2:])) / D
    return u.at[1:-1].set(inner)
