# Generated by bend-spike/v2/heat/emit.bend (Bend 2). Do not edit.
# Scheme: D u_i' = D u_i + p (u_{i-1} - 2 u_i + u_{i+1}),  r = alpha dt / dx^2 = p / D
# p = 1, D = 4
# raw IR:      Add(Scale(4, Var 1), Scale(1, Add(Var 0, Add(Scale(-2, Var 1), Var 2))))
# normal form: Lin{[1 2 1 ], 0}   (LAWS_HEAT.lin_sound: same meaning as the raw IR)
import jax
import jax.numpy as jnp

jax.config.update('jax_enable_x64', True)

P = 1
D = 4.0


@jax.jit
def step(u):
    # one explicit Euler step; u[0] and u[-1] are Dirichlet boundaries and stay put
    inner = ((1.0) * u[:-2] + (2.0) * u[1:-1] + (1.0) * u[2:] + (0.0)) / D
    return u.at[1:-1].set(inner)
